### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by MadhavBahl**

### CODE REVIEW

**Comment by XLAR-8** [comment]
Hi,
@MadhavBahlMD  can you please explain what this repo is for?
as it is mentioned "welcome all developers" please explain and provide any mode of communication , if possible. 
looking forward this to be something intresting and exciting to contribute to . 
logo is also cool .

**Comment by MadhavBahl** [comment]
Hey @XLAR-8, this repo will contain the community guidelines and other information regarding developers den.

Basic idea is to create a welcoming open source organization where people can enter, form teams for hackathons and other competitions, hold discussions, showcase projects, without any formalities. 

soon, I'll make a join the org repo and start sending invites 💯

**Comment by XLAR-8** [comment]
Hi ,
Thanks for replying .
I thinks it's a great idea to have a org. like this and I am looking
forward to it.

please do let me know if i can help in any way.

regards,
Ashok singh

**Comment by MadhavBahl** [comment]
Hey Ashok,
first of all, sorry for the late reply, little busy these days.
Also, Thanks a lot for the good words and yes, Developers Den (DD) will be an open org just like freeCodeCamp, so you can feel free to for teams, have discussions and start new awesome open source projects under the hood of  **Developers Den**, I will make a shareable invite link for GitHub org soon,

Also, for now there is no need for a separate slack workspace for DD, will have the discussions inside Code To Express's workspace itself, you can feel free to join: https://codetoexpress.tech/join/
Once the community grows, we can have separate workspaces. Also, if you spread the word about DD and C2E (https://www.facebook.com/CodeToExpress/), it'll be a great help 😄 

Thanks and Regards,
Madhav Bahl
(TheLeanProgrammer)

**Pull request merged**
